[settings]
download_dir = "/srv/Dev/Work/Tools/CMD"
proxy_prefix = "https://xget.uglyboy.cn/gh/"
log_level = "debug"

[packages.bun]
repo = "oven-sh/bun"
file_pattern = "bun-{os}-{arch}"
file_extension = "zip"

[packages.uv]
repo = "astral-sh/uv"
file_pattern = "uv-{arch}-unknown-{os}-gnu"
file_extension = "tar.gz"

[packages.opencode]
repo = "anomalyco/opencode"
file_pattern = "opencode-{os}-{arch}"
file_extension = "tar.gz"

[packages.lf]
repo = "gokcehan/lf"
file_pattern = "lf-{os}-{arch}"
file_extension = "tar.gz"
